# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'HW_18_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Quick'
  pod 'Nimble'
  pod 'OHHTTPStubs/Swift'
  pod 'RealmSwift'
  pod 'Magics'
  pod 'Alamofire'

  # Pods for HW_18

  target 'HW_18_testTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    pod 'OHHTTPStubs/Swift'
    pod 'RealmSwift'
    pod 'Magics'
    pod 'Alamofire'
  end

  target 'HW_18_testUITests' do
    # Pods for testing
  end

end
