# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'HW19' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

end
